name: flutter_pcm_sound_fork
description: Stream real-time PCM audio (16-bit integer) at low latency
version: 0.0.1
homepage: https://github.com/keyur2maru/flutter_pcm_sound

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=2.5.0"

platforms:
  android:
  ios:
  web:
  macos:

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  web: ^1.1.1

flutter:
  plugin:
    platforms:
      android:
        package: com.lib.flutter_pcm_sound
        pluginClass: FlutterPcmSoundPlugin
      ios:
        pluginClass: FlutterPcmSoundPlugin
      macos:
        pluginClass: FlutterPcmSoundPlugin
      web:
        pluginClass: FlutterPcmSoundWeb
        fileName: flutter_pcm_sound_web.dart

topics:
  - stream-audio
  - audio-streaming
  - pcm-audio
  - pcm-streaming
  - audio-streaming-flutter